version: '3.9'

services:

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=secret_passw0rd
      - POSTGRES_USER=auth_user
      - POSTGRES_DB=auth_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data: